### ISSUE TITLE
Can I NewGethSimulator from a running geth node ?

### ISSUE THREAD

**Issue by silsuer** [dialecticch/sibyl#3]
There is a bsc mainnet fullnode on my machine.
Now if I run the code below:
```
simulator, err := sibyl.NewGethSimulator("/path/to/geth/chaindata")
	if err != nil {
		log.Panic(err)
	}
```

I got error:
```
INFO [02-09|06:47:26.328] Allocated cache and file handles         database=/path/to/geth/chaindata
cache=48.00MiB handles=48 readonly=true
2022/02/09 06:47:26 resource temporarily unavailable
panic: resource temporarily unavailable
```

How to fix it ?

thx!

**Comment by decanus** [comment]
2 resources can't access the data at the same time.

**Comment by liusanchuan** [comment]
Hi, Is there anyone have the way to run this NewGethSimulator() function? 
I tested, the error is same as this issue.

**Comment by decanus** [comment]
you can't use it on a running node, leveldb doesn't support it.

**Comment by liusanchuan** [comment]
So maybe the availiable way is to embed the newEVM code into the running Geth Process, then grab info in one exec.
